import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const releases = [
  {
    version: '2026-09-30.1',
    migration: '0027_publish_legal_release.sql',
    reviewed: true,
  },
  {
    version: '2026-09-30.2',
    migration: '0028_google_analytics_privacy.sql',
    reviewed: true,
  },
];
const root = new URL('../../', import.meta.url);
const args = process.argv.slice(2);
if (
  args.length > 1 ||
  (args.length === 1 && !['--check', '--write'].includes(args[0]))
) {
  throw new Error('Usage: node tools/legal/release.mjs [--check|--write]');
}
for (const { version, migration, reviewed } of releases) {
  const terms = readFileSync(
    new URL(`docs/legal/${version}/terms.pl.md`, root),
    'utf8'
  );
  const privacy = readFileSync(
    new URL(`docs/legal/${version}/privacy.pl.md`, root),
    'utf8'
  );

  for (const [name, text] of [
    ['terms', terms],
    ['privacy', privacy],
  ]) {
    if (/SZKIC|DO UZUPEŁNIENIA|E2E fixture|\[data publikacji\]/i.test(text)) {
      throw new Error(`${name}: unfinished legal document`);
    }
    if (!text.includes(`Wersja: ${version}.`))
      throw new Error(`${name}: wrong version`);
    if (text.includes('$legal_terms$') || text.includes('$legal_privacy$')) {
      throw new Error(`${name}: SQL delimiter in document`);
    }
  }

  const sql = `-- ${
    reviewed ? 'Reviewed' : 'Prepared'
  } release ${version}; generated by tools/legal/release.mjs.
-- Publication time is the deployment time, not the commit date.
do $publish_legal$
begin
  update public.legal_releases set is_current = false where is_current;
  insert into public.legal_releases
    (version, locale, terms_text, privacy_text, published_at, is_current)
  values (
    '${version}', 'pl',
    $legal_terms$${terms}$legal_terms$,
    $legal_privacy$${privacy}$legal_privacy$,
    statement_timestamp(), true
  );
end;
$publish_legal$;
`;
  const destination = new URL(`supabase/migrations/${migration}`, root);
  if (args.length === 1 && args[0] === '--write') {
    if (reviewed) continue;
    writeFileSync(destination, sql);
    console.log(`Generated ${fileURLToPath(destination)}`);
  } else if (
    args.length === 0 ||
    (args.length === 1 && args[0] === '--check')
  ) {
    if (readFileSync(destination, 'utf8') !== sql) {
      throw new Error(
        'Legal migration differs from its reviewed Markdown sources'
      );
    }
    console.log(`Legal release ${version}: source and migration match`);
  } else {
    throw new Error('Usage: node tools/legal/release.mjs [--check|--write]');
  }
}
