import type { BlogGeneratedContent } from './blog-content';

// Generated by tools/scripts/generate-blog-content.mjs. Do not edit manually.
export const GENERATED_BLOG_CONTENT: BlogGeneratedContent = {
  "articles": [],
  "categories": []
};
