-- Reviewed release 2026-09-30.1; generated by tools/legal/release.mjs.
-- Publication time is the deployment time, not the commit date.
do $publish_legal$
begin
  update public.legal_releases set is_current = false where is_current;
  insert into public.legal_releases
    (version, locale, terms_text, privacy_text, published_at, is_current)
  values (
    '2026-09-30.1', 'pl',
    $legal_terms$# Regulamin Tickist

Wersja: 2026-09-30.1. Obowiązuje od daty publikacji pokazanej na stronie dokumentu.

## 1. Kto prowadzi Tickist

Tickist prowadzi Bartłomiej Borzucki jako prywatny projekt hobbystyczny w Polsce, bez firmy. Kontakt: hello@tickist.com.

Tickist służy do organizowania zadań i projektów. Udostępnia również współdzielenie, powiadomienia, import i eksport oraz autoryzowane integracje MCP. Publiczne strony można przeglądać bez konta; korzystanie z własnych zadań wymaga konta.

## 2. Bezpłatność i kod

Korzystanie z aplikacji jest bezpłatne. Dobrowolne wsparcie, jeśli zostanie udostępnione, nie jest warunkiem dostępu i nie daje dodatkowych funkcji. Warunki zewnętrznej platformy wsparcia będą opisane oddzielnie.

Kod aplikacji jest publiczny. Ten regulamin dotyczy korzystania z usługi na tickist.com.

## 3. Wymagania i rejestracja

Potrzebujesz połączenia internetowego, przeglądarki obsługującej JavaScript i technologie aplikacji oraz działającego adresu email. Przeglądarka musi umożliwiać przechowywanie danych niezbędnych do logowania. Nie gwarantujemy dostępności wszystkich funkcji offline.

Przed rejestracją możesz przeczytać i zapisać regulamin oraz politykę prywatności. Rejestracja wymaga podania emaila, ustalenia hasła, zaakceptowania regulaminu i potwierdzenia adresu email. Umowa zostaje zawarta po akceptacji regulaminu i skutecznym potwierdzeniu emaila, gdy konto staje się dostępne do korzystania. Zapoznanie się z polityką prywatności nie jest zbiorczą zgodą na przetwarzanie danych.

Możesz korzystać do celów osobistych, zawodowych i zespołowych. Działając w imieniu organizacji, powinieneś mieć odpowiednie uprawnienia. Nie ustanawiamy własnego minimalnego wieku. Osoby małoletnie korzystają z uwzględnieniem przepisów dotyczących zawierania umów, w tym udziału przedstawiciela ustawowego, gdy wymaga tego prawo.

## 4. Bezpieczeństwo i treści

Chroń hasło i tokeny dostępu. Zgłoś podejrzenie przejęcia konta na hello@tickist.com. Nie podszywaj się pod innych, nie uzyskuj dostępu do cudzych kont, nie przesyłaj złośliwego oprogramowania i nie zakłócaj celowo działania usługi.

Nie dostarczaj treści bezprawnych ani naruszających cudze prawa. Udostępniaj tylko dane, do których masz odpowiednie uprawnienia, i rozważnie nadawaj dostęp do projektów oraz integracji. Korzystanie zawodowe nie zwalnia z obowiązków dotyczących danych osób trzecich.

Zachowujesz prawa do swoich treści. Przetwarzamy je w zakresie potrzebnym do wykonania usługi: przechowania, wyświetlania uprawnionym osobom, wysyłania zamówionych powiadomień i zabezpieczenia danych.

Avatar ma publiczny adres pliku. Podłączony klient MCP może wykonywać operacje w granicach udzielonej autoryzacji; obowiązują również warunki jego dostawcy.

Podejrzenie treści bezprawnej lub naruszenia zgłoś na hello@tickist.com, wskazując miejsce, opis problemu i adres do odpowiedzi. Nie podawaj hasła ani tokenów. Operator rozpatruje zgłoszenie i w razie potrzeby prosi o wyjaśnienia; samo zgłoszenie nie przesądza o naruszeniu.

Przy potwierdzonym naruszeniu możemy wezwać do jego usunięcia, ograniczyć dostęp do konkretnych treści lub funkcji, a przy poważnych albo powtarzających się naruszeniach zawiesić lub zamknąć konto. Działanie powinno odpowiadać skali naruszenia i obejmować tylko niezbędny zakres. Jeśli trzeba niezwłocznie ochronić konta, dane lub działanie usługi albo wykonać obowiązek prawny, możemy zastosować konieczne zabezpieczenie przed zakończeniem wyjaśniania sprawy.

O ograniczeniu informujemy na email konta, podając przyczynę, zakres, okres lub warunek zakończenia oraz sposób zakwestionowania decyzji, z uwzględnieniem ograniczeń wynikających z prawa. Możesz poprosić o ponowne rozpatrzenie na hello@tickist.com, podając wyjaśnienia. Operator rozpatruje je w trybie reklamacji opisanym w punkcie 6; błędne lub nieuzasadnione ograniczenie cofamy. Nie ogranicza to możliwości skorzystania z właściwych środków prawnych.

## 5. Zakończenie korzystania i dane

Możesz zakończyć korzystanie i wystąpić o zamknięcie konta na remove-account@tickist.com. Samo wylogowanie nie usuwa konta. Przed zamknięciem możesz skorzystać z eksportu w ustawieniach.

Przed usunięciem możemy potrzebować proporcjonalnego potwierdzenia tożsamości. Dane współdzielone rozpatrujemy z uwzględnieniem praw innych osób; nie oznacza to bezterminowego wstrzymania żądania. Terminy odpowiedzi i zasady retencji opisuje [polityka prywatności](https://tickist.com/legal/privacy).

Nie zamykamy kont wyłącznie z powodu nieaktywności.

## 6. Działanie aplikacji i reklamacje

Tickist jest rozwijany i obsługiwany przez jedną osobę. Nie gwarantujemy nieprzerwanej dostępności, utrzymania projektu przez określony czas ani przejęcia jego obsługi przez następcę. Przerwy lub zakończenie działania mogą nastąpić również nagle, z przyczyn osobistych, zdrowotnych, technicznych lub bezpieczeństwa. Błędy i reklamacje zgłaszaj na hello@tickist.com. Opisz problem i podaj dane umożliwiające odpowiedź; nie przesyłaj hasła ani tokenu. Jeżeli będzie to potrzebne, poprosimy o dodatkowe informacje.

Odpowiadamy na reklamację w ciągu 14 dni od otrzymania, emailem na adres wskazany do kontaktu, bez naruszania obowiązujących terminów ustawowych.

Zalecamy regularny eksport ważnych danych. Nie wyłącza to odpowiedzialności wynikającej z prawa. Regulamin nie ogranicza bezwzględnie obowiązujących praw użytkownika, w tym praw konsumenta, gdy mają zastosowanie.

## 7. Zmiany i zamknięcie usługi

Pierwsza wersja obowiązuje od wskazanej daty publikacji, przed przyjmowaniem rejestracji na tych zasadach.

Zmiany regulaminu mogą wynikać ze zmian prawa, bezpieczeństwa lub funkcji wpływających na zasady korzystania z Tickista. O istotnej zmianie poinformujemy emailem, podając jej zakres, przyczynę i datę wejścia w życie. Informację przekażemy co najmniej 30 dni przed wejściem istotnej zmiany w życie. Przed wejściem zmiany w życie możesz zakończyć korzystanie i wyeksportować dane. Zmiany nie działają wstecz; wymagane prawem uprawnienia pozostają zachowane.

Operator może zdecydować o zakończeniu projektu, w szczególności z powodu braku możliwości dalszego utrzymania, kosztów lub przyczyn osobistych. Jeżeli okoliczności na to pozwolą, postara się uprzedzić użytkowników emailem i umożliwić eksport danych przed zamknięciem. Nie ustanawia się gwarantowanego okresu uprzedzenia o zamknięciu ani gwarancji kontynuacji przez inną osobę. Zasady te nie ograniczają obowiązków wynikających z bezwzględnie obowiązujących przepisów.

Przy zamknięciu obsługiwanym przez operatora dane kont, treści i kopie zapasowe podlegają usunięciu w ciągu 30 dni od zakończenia usługi, zgodnie z polityką prywatności. Regularnie eksportuj dane, które chcesz zachować; możliwość odzyskania ich po nagłym zakończeniu działania nie jest gwarantowana.

Polityka prywatności jest dostępna pod [tickist.com/legal/privacy](https://tickist.com/legal/privacy), a aktualny regulamin pod [tickist.com/legal/terms](https://tickist.com/legal/terms).

## 8. Dane przetwarzane na polecenie użytkownika

Jeżeli użytkownik działa jako administrator danych osobowych w treści zadań i projektów, np. w organizacji, akceptacja regulaminu obejmuje poniższe powierzenie operatorowi. Stroną jest użytkownik lub organizacja, którą ma prawo reprezentować. Użytkownik odpowiada za legalność danych i poleceń oraz obowiązki informacyjne; operator odpowiada za wykonanie swoich obowiązków jako podmiot przetwarzający.

Przedmiotem jest techniczna obsługa treści przez czas korzystania z konta i okres usuwania danych opisany w polityce. Obejmuje zapis, organizowanie, wyświetlanie uprawnionym osobom, zamówione powiadomienia, eksport i usunięcie. Kategorie osób i danych zależą od treści wybranych przez administratora: mogą obejmować użytkowników, współpracowników, klientów i kontakty oraz dane identyfikacyjne, kontaktowe i informacje w zadaniach. Nie oznacza to samodzielnego pozyskiwania takich danych przez operatora.

- Operator działa tylko według udokumentowanych poleceń administratora, obejmujących operacje w aplikacji i uzgodnienia emailem, także przy transferach. O obowiązku przetwarzania wynikającym z prawa informuje przed wykonaniem, chyba że prawo zabrania tej informacji. Informuje też niezwłocznie o poleceniu, które jego zdaniem narusza przepisy.
- Dostęp osób upoważnionych podlega poufności. Zabezpieczenia obejmują HTTPS, uwierzytelnianie, kontrolę dostępu w bazie, ograniczony dostęp operatora i szyfrowanie lokalnych backupów. Środki są dostosowywane do ryzyka; hobbystyczny charakter nie wyłącza obowiązków bezpieczeństwa.
- Administrator udziela ogólnej zgody na korzystanie z Supabase (baza i pliki), Cloudflare (dostarczanie i ochrona usługi) oraz AWS SES (zamówione wiadomości), z podwykonawcami wskazanymi w ich warunkach. Operator zapewnia odpowiednie zobowiązania dotyczące ochrony powierzonych danych i odpowiada za wykonanie obowiązków podprzetwarzającego. O dodaniu lub zastąpieniu podprzetwarzającego informuje emailem co najmniej 30 dni wcześniej, umożliwiając uzasadniony sprzeciw; gdy nie można uzgodnić rozwiązania, administrator może zakończyć korzystanie i wyeksportować dane.
- Operator pomaga w realizacji praw osób, zabezpieczeniach, obsłudze naruszeń i ocenach wymaganych przez art. 32–36 RODO, odpowiednio do charakteru przetwarzania i dostępnych informacji. O naruszeniu powierzonych danych zawiadamia administratora bez zbędnej zwłoki po jego stwierdzeniu.
- Operator udostępnia informacje potrzebne do wykazania wykonania powierzenia i umożliwia uzgodnione audyty, w tym inspekcje administratora lub jego audytora, z ochroną danych innych użytkowników.
- Po zakończeniu powierzenia, według wyboru administratora, umożliwia zwrot danych lub je usuwa; usuwa także kopie zgodnie z okresem backupów. Eksport aplikacji nie zastępuje pomocy operatora w zwrocie danych poza jego zakresem. Wyjątek dotyczy wyłącznie danych wymaganych konkretnym przepisem.

Własna obsługa konta, bezpieczeństwa i korespondencji operatora jest opisana oddzielnie w polityce prywatności. Nie zmienia to instrukcji dotyczących powierzonych treści.
$legal_terms$,
    $legal_privacy$# Polityka prywatności Tickist

Wersja: 2026-09-30.1. Obowiązuje od daty publikacji pokazanej na stronie dokumentu.

## 1. Administrator i kontakt

Administratorem danych dotyczących kont, działania usługi i korespondencji jest Bartłomiej Borzucki, prowadzący Tickist samodzielnie jako prywatny projekt hobbystyczny w Polsce. W sprawach prywatności napisz na hello@tickist.com, a w sprawie usunięcia konta na remove-account@tickist.com.

## 2. Jakie dane przetwarzamy i dlaczego

| Dane i sytuacja                                                                    | Cel i podstawa przetwarzania                                                                                                               |
| ---------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------ |
| Email, dane uwierzytelniania, identyfikator konta, strefa czasowa                  | Rejestracja, logowanie, odzyskiwanie dostępu i obsługa konta — wykonanie umowy, art. 6 ust. 1 lit. b RODO.                                 |
| Zadania, projekty, tagi, terminy, ustawienia, aktywność, opcjonalna nazwa i avatar | Udostępnienie funkcji aplikacji — wykonanie umowy w zakresie niezbędnych danych użytkownika, art. 6 ust. 1 lit. b.                         |
| Adres email, preferencje i treść powiadomień                                       | Wiadomości dotyczące konta, przypomnienia i wybrane podsumowania — wykonanie umowy, art. 6 ust. 1 lit. b.                                  |
| Wersja zaakceptowanego regulaminu, identyfikator konta i czas akceptacji           | Udokumentowanie warunków korzystania — uzasadniony interes wykazania zawarcia umowy, art. 6 ust. 1 lit. f.                                 |
| Dane techniczne połączenia, w tym IP i logi bezpieczeństwa                         | Ochrona usługi i wyjaśnianie błędów — uzasadniony interes bezpieczeństwa, art. 6 ust. 1 lit. f.                                            |
| Korespondencja dotycząca konta lub reklamacji                                      | Obsługa umowy — art. 6 ust. 1 lit. b; dokumentacja niezbędna w konkretnym sporze — uzasadniony interes ochrony praw, art. 6 ust. 1 lit. f. |
| Żądania dotyczące praw do danych                                                   | Wykonanie obowiązków administratora — art. 6 ust. 1 lit. c w związku z RODO.                                                               |

Dane podajesz podczas rejestracji i korzystania z aplikacji. Email i dane potrzebne do logowania są konieczne do korzystania z konta; nazwa wyświetlana i avatar są opcjonalne. Dane techniczne powstają przy połączeniu z serwisem.

Zaproszenia do projektu trafiają do osób posiadających konto Tickist. Właściciel projektu podaje email zapraszanej osoby; zapisujemy informację o zaproszeniu, zapraszającym i projekcie. Osobie bez konta ta funkcja nie wysyła zaproszenia. Obsługa zaproszeń opiera się na uzasadnionym interesie umożliwienia współpracy w aplikacji, art. 6 ust. 1 lit. f RODO. Zaproszenie możesz przyjąć lub odrzucić.

Treści zadań i projektów pochodzą od użytkowników. Użytkownik określa cel ich zapisania oraz osoby, którym je udostępnia. Jeżeli działa jako administrator danych, np. klientów lub pracowników, operator przetwarza te treści na jego polecenie, zgodnie z zasadami powierzenia w regulaminie. To użytkownik odpowiada za podstawę przetwarzania i poinformowanie tych osób. Operator nie wykorzystuje powierzonych treści do własnego marketingu ani profilowania. W sprawie danych w treści możesz skontaktować się z ich administratorem lub z nami — pomożemy skierować żądanie do właściwej osoby. Przy prywatnym korzystaniu przetwarzamy informacje o innych osobach wyłącznie w zakresie niezbędnym do udostępnienia zapisanych przez użytkownika treści, na podstawie uzasadnionego interesu umożliwienia tej funkcji, art. 6 ust. 1 lit. f RODO; możesz wnieść sprzeciw.

## 3. Kto otrzymuje dane

| Usługa                            | Zastosowanie w Tickist                                                                                                        |
| --------------------------------- | ----------------------------------------------------------------------------------------------------------------------------- |
| Supabase                          | Konto, baza danych i pliki; region projektu: eu-west-2, Londyn.                                                               |
| Cloudflare                        | Dostarczanie i zabezpieczenie aplikacji, Workers, pomiar ruchu i wydajności oraz przekierowywanie poczty przez Email Routing. |
| AWS SES                           | Wysyłka wiadomości dotyczących usługi; region: eu-north-1, Sztokholm.                                                         |
| Google — prywatny Gmail operatora | Odbieranie i obsługa korespondencji z adresów kontaktowych, przekierowanej przez Cloudflare.                                  |

Udostępnione projekty są dostępne osobom zgodnie z nadanymi uprawnieniami. Avatar ma publiczny adres pliku: osoba posiadająca ten adres może go otworzyć.

Podłączony przez Ciebie klient MCP może uzyskać dostęp do danych i wykonywać operacje w granicach udzielonej autoryzacji. Dostawca takiego klienta ma własne zasady przetwarzania. Dane mogą też otrzymać uprawnione organy, gdy wymagają tego przepisy.

Dostawcy infrastruktury przetwarzają dane dla operatora zgodnie ze swoimi warunkami i umowami powierzenia; w zakresie własnych obowiązków i bezpieczeństwa mogą działać jako niezależni administratorzy. Korespondencja trafia do konsumenckiego Gmaila, objętego warunkami i polityką Google; nie jest to Google Workspace ani usługa objęta jego umową powierzenia. Nie przesyłaj w zgłoszeniach zbędnych kopii zadań lub danych innych osób.

Szyfrowane kopie zapasowe znajdują się na komputerze operatora, bez synchronizacji do chmury.

## 4. Przekazywanie poza Europejski Obszar Gospodarczy

Baza Supabase znajduje się w Wielkiej Brytanii, objętej decyzją Komisji Europejskiej o odpowiednim stopniu ochrony. SES używa regionu w Szwecji. Dostawcy mogą też przetwarzać dane poza EOG, w tym w USA; region serwera nie wyklucza dostępu wsparcia lub podwykonawców.

Dla transferów objętych powierzeniem warunki [Supabase](https://supabase.com/legal/customer-resources/data-processing-addendum), [Cloudflare](https://www.cloudflare.com/cloudflare-customer-dpa/) i [AWS](https://aws.amazon.com/service-terms/) przewidują standardowe klauzule umowne Komisji Europejskiej, gdy transfer wymaga takich zabezpieczeń. Dla państw lub odbiorców objętych właściwą decyzją o adekwatności zastosowanie ma ta decyzja. Konsumencki Gmail podlega [polityce Google](https://policies.google.com/privacy), opisującej globalne przetwarzanie i mechanizmy transferów Google. Informacje o właściwych zabezpieczeniach i ich kopię lub odnośnik uzyskasz pod hello@tickist.com; w udostępnianych dokumentach chronimy dane innych osób i informacje poufne.

## 5. Jak długo przechowujemy dane

| Dane                                      | Uzgodniony okres                                                                                                                                       |
| ----------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------ |
| Konto i zapisane treści                   | Przez okres korzystania z konta, z uwzględnieniem wcześniejszego usuwania treści i realizacji praw. Kont nie usuwamy wyłącznie z powodu nieaktywności. |
| Potwierdzenie akceptacji regulaminu       | Do usunięcia konta.                                                                                                                                    |
| Powiadomienia w aplikacji                 | 180 dni od utworzenia.                                                                                                                                 |
| Nieprzyjęte zaproszenia                   | Wygasają po 30 dniach; odrzucone usuwamy po 30 dniach od odrzucenia. Zaakceptowane członkostwa pozostają przez okres współpracy.                       |
| Historia aktywności i MCP                 | 90 dni od zdarzenia.                                                                                                                                   |
| Historia zakończonej wysyłki emaili       | 30 dni od wysłania lub zakończenia obsługi błędu; wiadomości oczekujące na wysłanie pozostają do zakończenia obsługi.                                  |
| Lokalne szyfrowane backupy                | Najwyżej 30 dni od utworzenia.                                                                                                                         |
| Zwykła korespondencja pomocy i załączniki | 12 miesięcy od zamknięcia sprawy.                                                                                                                      |

Czyszczenie historii aplikacji jest uruchamiane codziennie po przekroczeniu okresu; nie oznacza usunięcia dokładnie w sekundzie upływu terminu. Nieudany przebieg wymaga ponowienia. Niejednoznaczne historyczne zapisy wysyłki sprawdzamy i usuwamy ręcznie, zamiast przypisywać je błędnemu kontu. Po usunięciu pełnej historii emaila do usunięcia konta pozostaje techniczny skrót operacji, powiązany z identyfikatorem konta, aby zapobiec ponownej wysyłce. Nie zawiera adresu email, tematu ani treści.

W Cloudflare Web Analytics pełne dane pomiarowe są przechowywane przez 7 dni; część danych dostawca zachowuje następnie do dłuższych zestawień. Panel udostępnia pomiary z ostatnich 6 miesięcy. Ograniczenie ilości danych przez próbkowanie nie oznacza samo w sobie ich anonimizacji ani usunięcia wszystkich zapisów po 7 dniach.

W planie Free Supabase udostępnia operatorowi logi z ostatniego dnia. Są to okresy dostępności logów dla operatora, a nie zapewnienie o usunięciu wszystkich danych przechowywanych niezależnie przez dostawcę.

Cloudflare Workers Logs przechowuje logi przez 3 dni w planie Workers Free lub 7 dni w Workers Paid. Nie tworzymy osobnego długoterminowego archiwum tych logów. Są one odrębne od pomiarów Web Analytics.

Dokumentację zamkniętych żądań dotyczących danych przechowujemy w ramach 12-miesięcznego okresu korespondencji. Jeżeli trwa spór lub postępowanie, zachowujemy niezbędną dokumentację do jego prawomocnego zakończenia, a dłużej tylko gdy konkretny przepis tego wymaga. Dokumentacja nie oznacza zachowania całej kopii konta.

Usunięcie konta nie oznacza natychmiastowego wymazania istniejących backupów; kopie wygasają w ramach ich okresu przechowywania. Po odtworzeniu kopii ponownie stosujemy zrealizowane usunięcia przed udostępnieniem odtworzonej bazy użytkownikom.

Przy zakończeniu usługi obsługiwanym przez operatora dane Tickista pozostające pod jego kontrolą — konta, zadania, projekty, pliki, historia, lokalne backupy i korespondencja dotycząca Tickista — są usuwane w ciągu 30 dni od zamknięcia. Kopie zapasowe nie otrzymują dodatkowych 30 dni od późniejszego wykonania kopii. Dane, których dalsze przechowywanie jest wymagane konkretnym obowiązkiem prawnym, zachowujemy wyłącznie w niezbędnym zakresie i przez wymagany okres. Własne eksporty użytkowników i niezależne zapisy dostawców nie są kopiami, które operator może samodzielnie usunąć.

## 6. Twoje prawa

Na zasadach RODO możesz żądać dostępu i kopii danych, sprostowania, usunięcia, ograniczenia przetwarzania oraz przenoszenia danych. Możesz wnieść sprzeciw wobec przetwarzania opartego na uzasadnionym interesie. Zgodę, jeśli jest podstawą konkretnego przetwarzania, możesz wycofać bez wpływu na zgodność wcześniejszego przetwarzania z prawem. Nie wszystkie prawa dotyczą każdej sytuacji.

Napisz na hello@tickist.com lub remove-account@tickist.com. Możemy poprosić o proporcjonalne potwierdzenie tożsamości; nie przesyłaj hasła ani tokenów. Odpowiadamy bez zbędnej zwłoki, co do zasady w ciągu miesiąca od otrzymania żądania. Ewentualne przedłużenie następuje na zasadach RODO, z poinformowaniem o przyczynie. Współdzielone dane rozpatrujemy z uwzględnieniem praw innych osób.

Możesz wnieść skargę do Prezesa Urzędu Ochrony Danych Osobowych lub innego właściwego organu nadzorczego.

## 7. Pamięć przeglądarki i analityka

Tickist zapisuje w pamięci przeglądarki sesję logowania, motyw i wybraną przestrzeń roboczą. Sesja jest utrzymywana i odświeżana; ustawienia nie mają automatycznego terminu wygaśnięcia. Stan odzyskiwania hasła zapisujemy w pamięci sesji i usuwamy przy zakończeniu tego procesu. Pamięć podręczna zawiera również pliki aplikacji; zmienia się przy aktualizacjach.

Możesz usunąć dane witryny w przeglądarce. Może to wylogować konto i usunąć lokalne ustawienia, ale nie usuwa konta ani treści zapisanych na serwerze.

Cloudflare Web Analytics mierzy ruch i wydajność po Twojej dobrowolnej zgodzie, także po zalogowaniu. Podstawą jest zgoda, art. 6 ust. 1 lit. a RODO; odmowa nie ogranicza funkcji aplikacji. Przekazuje adresy odwiedzanych widoków i stron odsyłających (mogą zawierać identyfikator projektu), pomiary wydajności oraz informacje o przeglądarce i systemie.

Przycisk „Privacy settings” pozwala zmienić wybór. Zgodę możesz wycofać równie łatwo jak ją wyrazić; wycofanie odświeża stronę, żeby zatrzymać wcześniej uruchomiony pomiar. Przed odświeżeniem zapisz rozpoczętą edycję. Decyzję przechowujemy lokalnie przez 180 dni, po czym przy ponownym otwarciu pytamy o nią ponownie. Bez dostępu do pamięci przeglądarki wybór może dotyczyć tylko bieżącej sesji. Parametr `tickist_analytics=off` zabezpiecza wycofanie zgody także przy problemach z zapisem ustawienia.

Obecnie nie prowadzimy newslettera ani wysyłki promocyjnej. Dodanie nowych narzędzi pomiarowych lub marketingowych będzie wymagało odpowiedniej aktualizacji informacji i zgód, jeżeli są potrzebne.

## 8. Zmiany polityki

Aktualna polityka będzie dostępna pod [tickist.com/legal/privacy](https://tickist.com/legal/privacy). O istotnych zmianach sposobu przetwarzania poinformujemy użytkowników. Aktualizacja tekstu nie zastępuje nowej podstawy prawnej lub zgody, jeśli są potrzebne.
$legal_privacy$,
    statement_timestamp(), true
  );
end;
$publish_legal$;
