export const DATASET_VERSION = '2026-07-v1';
export const DEMO_SEED_ID = 'tickist-screenshots';

export const DEMO_USER = Object.freeze({
  email: 'demo@tickist.com',
  username: 'maya_chen_demo',
  fullName: 'Maya Chen',
  age: 34,
  city: 'Mountain View, California',
  timezone: 'America/Los_Angeles',
});

export const TAGS = Object.freeze([
  'Next up',
  'Deep work',
  'Waiting',
  'Errands',
  'Health',
  'Home',
  'People',
  'Weekend',
  'Learning',
  'Finance',
  'Travel',
  'Quick win',
]);

export const PROJECTS = Object.freeze([
  {
    key: 'aurora',
    name: 'Aurora Launch',
    description:
      'Ship the fall release of Aurora with a calm, measurable rollout.',
    color: '#7c3aed',
    icon: 'rocket',
    tasks: [
      'Finalize the launch readiness checklist',
      'Review beta adoption with analytics',
      'Confirm the staged rollout percentages',
      'Draft the launch-day team update',
      'Book the go/no-go review',
      'Close the remaining accessibility gaps',
    ],
  },
  {
    key: 'ai-beta',
    name: 'AI Assistant Beta',
    description: 'Validate the assistant experience with design partners.',
    color: '#2563eb',
    icon: 'sparkles',
    tasks: [
      'Synthesize feedback from design partners',
      'Review hallucination evaluation results',
      'Define the beta exit criteria',
      'Pair with Priya on prompt observability',
      'Prepare the customer feedback session',
      'Prioritize the next evaluation dataset',
    ],
  },
  {
    key: 'team',
    name: 'Hiring & Team',
    description: 'Grow and support the product engineering team.',
    color: '#0891b2',
    icon: 'users',
    tasks: [
      'Write the staff engineer interview rubric',
      'Schedule one-on-ones for next week',
      'Review the onboarding plan for Elena',
      'Send interview feedback to recruiting',
      'Plan the quarterly team offsite',
      'Update the engineering growth framework',
    ],
  },
  {
    key: 'engineering',
    name: 'Engineering Excellence',
    description: 'Reliability, developer experience, and sustainable delivery.',
    color: '#0f766e',
    icon: 'wrench',
    tasks: [
      'Review the API latency budget',
      'Choose owners for flaky test cleanup',
      'Document the incident review template',
      'Audit production alert thresholds',
      'Plan the dependency upgrade window',
      'Measure pull request cycle time',
    ],
  },
  {
    key: 'research',
    name: 'Customer Research',
    description: 'Stay close to customers and the problems they are solving.',
    color: '#db2777',
    icon: 'message-circle',
    tasks: [
      'Recruit five workflow research participants',
      'Summarize the healthcare customer interview',
      'Tag themes in the research repository',
      'Share the monthly insight brief',
      'Prepare questions for the founder panel',
      'Follow up with the logistics design partner',
    ],
  },
  {
    key: 'q3',
    name: 'Q3 Planning',
    description: 'Turn company priorities into a focused product plan.',
    color: '#ea580c',
    icon: 'calendar',
    tasks: [
      'Draft the Q3 product narrative',
      'Reconcile roadmap capacity with staffing',
      'Review dependencies with infrastructure',
      'Publish the planning decision log',
      'Prepare the executive roadmap review',
      'Define success metrics for each bet',
    ],
  },
  {
    key: 'talks',
    name: 'Conference Talks',
    description:
      'Prepare practical talks about responsible AI product delivery.',
    color: '#9333ea',
    icon: 'mic',
    tasks: [
      'Outline the responsible AI talk',
      'Record a ten-minute rehearsal',
      'Request feedback on the opening story',
      'Design the evaluation flywheel slide',
      'Submit the speaker bio and headshot',
      'Practice the audience Q&A section',
    ],
  },
  {
    key: 'career',
    name: 'Career Growth',
    description:
      'Build leadership range without losing hands-on product judgment.',
    color: '#4f46e5',
    icon: 'trending-up',
    tasks: [
      'Write the midyear self-reflection',
      'Ask Dana for leadership feedback',
      'Update the accomplishment journal',
      'Choose a product leadership coach',
      'Read notes from the strategy workshop',
      'Plan the next mentoring conversation',
    ],
  },
  {
    key: 'apartment',
    name: 'Mountain View Apartment',
    description:
      'Keep the apartment comfortable, organized, and easy to maintain.',
    color: '#16a34a',
    icon: 'home',
    tasks: [
      'Schedule the air conditioner service',
      'Measure the balcony for planters',
      'Replace the kitchen water filter',
      'Donate the unused hallway cabinet',
      'Ask the landlord about window seals',
      'Organize the storage closet',
    ],
  },
  {
    key: 'office',
    name: 'Home Office',
    description: 'Create a healthy space for focused work and writing.',
    color: '#0284c7',
    icon: 'monitor',
    tasks: [
      'Order a monitor arm',
      'Calibrate the standing desk presets',
      'Hide the charging cables',
      'Test the new video call lighting',
      'Frame the Yosemite print',
      'Set up a distraction-free writing profile',
    ],
  },
  {
    key: 'fitness',
    name: 'Health & Fitness',
    description: 'Sustainable strength, mobility, sleep, and preventive care.',
    color: '#dc2626',
    icon: 'heart',
    tasks: [
      'Book the annual physical',
      'Complete three strength sessions this week',
      'Refill the daily sunscreen',
      'Review sleep trends from the last month',
      'Schedule a dental cleaning',
      'Plan protein-rich weekday lunches',
    ],
  },
  {
    key: 'outdoors',
    name: 'Trails & Outdoors',
    description: 'Make the most of Bay Area trails and weekends outside.',
    color: '#15803d',
    icon: 'mountain',
    tasks: [
      'Choose Saturday trail at Rancho San Antonio',
      'Replace the hiking water filter',
      'Check Mount Tam permit dates',
      'Clean the trail shoes',
      'Invite Sofia to the coastal hike',
      'Download the offline trail map',
    ],
  },
  {
    key: 'ev',
    name: 'EV & Transportation',
    description: 'Maintain the car and make local travel frictionless.',
    color: '#0d9488',
    icon: 'car',
    tasks: [
      'Rotate the EV tires',
      'Renew the FasTrak payment card',
      'Compare off-peak charging plans',
      'Clean the cabin air filter',
      'Add the insurance card to the glove box',
      'Check Caltrain service for Friday',
    ],
  },
  {
    key: 'cooking',
    name: 'Food & Cooking',
    description: 'Cook more often and keep weekday meals interesting.',
    color: '#ca8a04',
    icon: 'utensils',
    tasks: [
      'Plan dinners for the workweek',
      'Try the miso salmon recipe',
      'Restock spices from the farmers market',
      'Sharpen the chef knife',
      'Freeze two portions of lentil soup',
      'Book a table for Sunday brunch',
    ],
  },
  {
    key: 'family',
    name: 'Family & Friends',
    description: 'Be intentional about the people who matter.',
    color: '#e11d48',
    icon: 'heart-handshake',
    tasks: [
      'Call Mom before Sunday dinner',
      'Plan a birthday dinner for Leah',
      'Send photos from the Tahoe weekend',
      'Confirm the July board game night',
      'Mail the graduation card to Kevin',
      'Check in with Anna after her move',
    ],
  },
  {
    key: 'finance',
    name: 'Financial Planning',
    description: 'Keep savings, benefits, and long-term goals on track.',
    color: '#059669',
    icon: 'wallet',
    tasks: [
      'Review the quarterly investment allocation',
      'Increase the emergency fund transfer',
      'Download the latest RSU statement',
      'Compare umbrella insurance quotes',
      'Update the annual giving budget',
      'Archive the June credit card statements',
    ],
  },
  {
    key: 'japan',
    name: 'Japan Trip',
    description: 'Plan an autumn trip through Tokyo, Kyoto, and Naoshima.',
    color: '#be123c',
    icon: 'plane',
    tasks: [
      'Book the Tokyo hotel',
      'Reserve the Naoshima museum tickets',
      'Compare rail pass options',
      'Create the Kyoto food map',
      'Check passport expiration date',
      'Ask Mei for Tokyo recommendations',
    ],
  },
  {
    key: 'tahoe',
    name: 'Tahoe Weekends',
    description: 'Simple plans for mountain weekends with friends.',
    color: '#0369a1',
    icon: 'trees',
    tasks: [
      'Find an August cabin weekend',
      'Service the camping stove',
      'Share the packing list with the group',
      'Reserve paddleboards for Saturday',
      'Check wildfire conditions',
      'Plan the drive around Friday traffic',
    ],
  },
  {
    key: 'learning',
    name: 'Learning',
    description: 'A steady reading and coursework practice.',
    color: '#7e22ce',
    icon: 'book-open',
    tasks: [
      'Finish the causal inference chapter',
      'Take notes on the AI policy lecture',
      'Complete the SQL optimization exercise',
      'Choose the next nonfiction book',
      'Review spaced repetition cards',
      'Attend the Stanford design seminar',
    ],
  },
  {
    key: 'side-project',
    name: 'Neighborhood Guide',
    description: 'A small side project for sharing quiet Bay Area places.',
    color: '#c026d3',
    icon: 'map',
    tasks: [
      'Sketch the neighborhood guide homepage',
      'Interview two local coffee shop owners',
      'Add accessibility notes to place cards',
      'Choose a lightweight hosting setup',
      'Write the first Mountain View guide',
      'Photograph the Stevens Creek trail',
    ],
  },
  {
    key: 'volunteering',
    name: 'Community & Volunteering',
    description: 'Support local food access and early-career mentorship.',
    color: '#65a30d',
    icon: 'hand-heart',
    tasks: [
      'Confirm the Second Harvest shift',
      'Review Naomi’s mentorship goals',
      'Share resume feedback with Luis',
      'Register for the creek cleanup',
      'Choose a fall nonprofit donation',
      'Invite coworkers to volunteer day',
    ],
  },
  {
    key: 'photography',
    name: 'Photography',
    description: 'Practice observation and make a small body of local work.',
    color: '#475569',
    icon: 'camera',
    tasks: [
      'Cull the foggy morning photo set',
      'Print three black-and-white studies',
      'Clean the camera sensor',
      'Plan a golden-hour walk in Palo Alto',
      'Back up the latest RAW files',
      'Submit one image to the local show',
    ],
  },
  {
    key: 'reading',
    name: 'Reading List',
    description: 'Books and long-form pieces worth protecting time for.',
    color: '#92400e',
    icon: 'library',
    tasks: [
      'Read the saved climate adaptation essay',
      'Finish Tomorrow, and Tomorrow, and Tomorrow',
      'Borrow the next book club pick',
      'Organize highlights from the strategy book',
      'Read the long-form profile of Fei-Fei Li',
      'Send two book recommendations to Jordan',
    ],
  },
  {
    key: 'hosting',
    name: 'Hosting & Gatherings',
    description: 'Low-stress dinners and gatherings at home.',
    color: '#f97316',
    icon: 'party-popper',
    tasks: [
      'Plan the summer patio dinner',
      'Ask guests about dietary restrictions',
      'Borrow folding chairs from Sofia',
      'Make the farmers market shopping list',
      'Choose a make-ahead dessert',
      'Send the parking instructions',
    ],
  },
  {
    key: 'admin',
    name: 'Life Admin',
    description: 'Documents, appointments, and small obligations.',
    color: '#64748b',
    icon: 'clipboard-check',
    tasks: [
      'Renew the library card',
      'Scan the signed lease addendum',
      'Update the emergency contact form',
      'Cancel the unused streaming trial',
      'Return the online clothing order',
      'File the vehicle registration receipt',
    ],
  },
  {
    key: 'garden',
    name: 'Balcony Garden',
    description: 'Grow herbs and California-friendly plants in a small space.',
    color: '#22c55e',
    icon: 'sprout',
    tasks: [
      'Repot the basil and mint',
      'Choose two drought-tolerant flowers',
      'Install the drip watering timer',
      'Trim the rosemary',
      'Pick up compost from the city',
      'Move the tomatoes into larger pots',
    ],
  },
  {
    key: 'routines',
    name: 'Weekly Routines',
    description: 'Small recurring systems that keep the week steady.',
    color: '#14b8a6',
    icon: 'repeat',
    projectType: 'routine',
    tasks: [
      'Plan the week on Sunday evening',
      'Clear the email follow-up folder',
      'Water the balcony plants',
      'Review the household grocery list',
      'Prepare clothes for the workweek',
      'Back up the laptop',
    ],
  },
  {
    key: 'someday',
    name: 'Someday / Maybe',
    description: 'Ideas worth keeping without pretending they are commitments.',
    color: '#8b5cf6',
    icon: 'cloud',
    projectType: 'someday',
    tasks: [
      'Take a ceramics wheel class',
      'Learn conversational Japanese',
      'Try a weeklong writing retreat',
      'Build a reading nook by the window',
      'Visit Channel Islands National Park',
      'Host a neighborhood photo walk',
    ],
  },
  {
    key: 'future-home',
    name: 'Future Home Ideas',
    description: 'Research for a possible Bay Area home in a few years.',
    color: '#a16207',
    icon: 'building',
    projectType: 'someday',
    tasks: [
      'Compare walkable Peninsula neighborhoods',
      'List must-haves for a future home',
      'Estimate a realistic down payment range',
      'Research heat pump incentives',
      'Save examples of compact home offices',
      'Learn about seismic retrofit basics',
    ],
  },
]);

export const INBOX_TASKS = Object.freeze([
  'Reply to Marcus about Thursday coffee',
  'Pick up dry cleaning on Castro Street',
  'Send the updated bio to the event organizer',
  'Buy a birthday card for Leah',
  'Book a haircut for next week',
  'Return the library books',
  'Review the dentist estimate',
  'Add the farmers market to Saturday plans',
  'Forward the receipt to the benefits team',
  'Choose a thank-you gift for the hosts',
  'Schedule the package pickup',
  'Save the recipe Dana recommended',
  'Check the concert ticket release time',
  'Bring reusable bags to the car',
]);
